### ISSUE TITLE
Can't select osu! directory in v0.9.4

### ISSUE THREAD

**Issue by 4samsamAC** [ShikkesoraSIM/anti-mindblock#12]
I'm encountering an error when attempting to select the osu! directory. This error did not occur in the v0.9.3.

Here's the complete error message I'm receiving:
```python
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python312\Lib\tkinter\__init__.py", line 1962, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "D:\anti-mindblock\reverse.py", line 290, in select_osu_directory
    dir_path = tk.filedialog.askdirectory(title="Select osu! Directory")
               ^^^^^^^^^^^^^
AttributeError: module 'tkinter' has no attribute 'filedialog'
```
I suspect this error was caused by the removed line:
```python 
from tkinter import ttk, font as tkFont, filedialog, Listbox, messagebox
```

**Comment by 4samsamAC** [comment]
Maybe I found a fix by simply importing the filedialog module:
```python
16. import tkinter as tk
17. from tkinter import messagebox, filedialog
18. import webbrowser
```
And using the module directly:
```python
290. def select_osu_directory():
291.     dir_path = filedialog.askdirectory(title="Select osu! Directory")
292.     if not dir_path:
```

**Comment by ShikkesoraSIM** [comment]
Oh thanks for reporting this!
